#pragma once
enum class Scope
{
	Local = 0,
	Tree = 1,
	Global = 2,
};

enum class TeamEnum
{
	TEAM_UNKOWN = 0,
	TEAM_ORDER = 100,
	TEAM_CHAOS = 200,
	TEAM_NEUTRAL = 300,
};

enum class UnitType
{
	MISSILE_UNIT = 32769,
	MINION_UNIT = 3073,
	HERO_UNIT = 5121,
	TURRET_UNIT = 9217,
	INHIBITOR_UNIT = 131077,
	HQ_UNIT = 4,
	CAPTURE_POINT_UNIT = 5,
	UNKNOWN_UNIT = 6,
	SHOP_UNIT = 5
};

enum class VariableType
{
	Value = 1,
	Reference = 2,
};

enum class UIElement
{
	UI_MINIMAP = 0,
	UI_QUESTS = 1,
	UI_TIPS = 2,
	UI_CHARACTER_INFO = 3,
	UI_BUFFS = 4,
	UI_ABILITY_4 = 5,
	UI_RECALL = 6,
	UI_SHOP = 7,
	UI_SKILLPOINT1 = 8,
	UI_GOLD = 9,
	UI_ASSISTS = 10,
	UI_PASSIVE = 11,
	UI_SKILLPOINT2 = 12,
	UI_SKILLPOINT3 = 13,
	UI_SKILLPOINT4 = 14,
};

enum class UnitTeam
{
	ALLY_TEAM = 0,
	ENEMY_TEAM = 1,
	NEUTRAL_TEAM = 2,
	UNKNOWN_TEAM = 3,
};

enum class TooltipVarEnum
{
	F1 = 0,
	F2 = 1,
	F3 = 2,
	F4 = 3,
	F5 = 4,
	F6 = 5,
	F7 = 6,
	F8 = 7,
	F9 = 8,
	F10 = 9,
	F11 = 10,
	F12 = 11,
	F13 = 12,
	F14 = 13,
	F15 = 14,
	F16 = 15,
};

enum class SpellParameterInt
{
	SPELLPARAM_TARGETTINGTYPE = 17,
	SPELLPARAM_MAXAMMOCOUNT = 47,
	SPELLPARAM_CASTTYPE = 50,
};

enum class SpellbookTypeEnum
{
	SPELLBOOK_CHAMPION = 0,
	SPELLBOOK_SUMMONER = 1,
	SPELLBOOK_UNKNOWN = 2,
};

enum class StatEvent
{
	NODE_CAPTURE = 0,
	NODE_CAPTURE_ASSIST = 1,
	NODE_NEUTRALIZE = 2,
	NODE_NEUTRALIZE_ASSIST = 3,
	TEAM_OBJECTIVE = 4,
};

enum class SpawnLocationType
{
	SPAWN_HQ = 0,
	SPAWN_LOCATION = 1,
	SPAWN_BARRACKS_LANE_R = 2,
	SPAWN_BARRACKS_LANE_C = 3,
	SPAWN_BARRACKS_LANE_L = 4,
	SPAWN_DAMPENER_LANE_R = 5,
	SPAWN_DAMPENER_LANE_C = 6,
	SPAWN_DAMPENER_LANE_L = 7,
	SPAWN_SHOP = 8,
};

enum class SpellParameterFloat
{
	SPELLPARAM_EFFECT1AMOUNT = 3,
	SPELLPARAM_EFFECT2AMOUNT = 4,
	SPELLPARAM_EFFECT3AMOUNT = 5,
	SPELLPARAM_EFFECT4AMOUNT = 6,
	SPELLPARAM_EFFECT5AMOUNT = 7,
	SPELLPARAM_EFFECT6AMOUNT = 8,
	SPELLPARAM_EFFECT7AMOUNT = 9,
	SPELLPARAM_EFFECT8AMOUNT = 10,
	SPELLPARAM_EFFECT9AMOUNT = 11,
	SPELLPARAM_EFFECT10AMOUNT = 12,
	SPELLPARAM_COOLDOWN = 13,
	SPELLPARAM_MANACOST = 14,
	SPELLPARAM_CASTRANGE = 16,
	SPELLPARAM_COEFFICIENT = 18,
	SPELLPARAM_COEFFICIENT2 = 19,
	SPELLPARAM_LOCATIONTARGETTINGWIDTH = 23,
	SPELLPARAM_LOCATIONTARGETTINGLENGTH = 24,
	SPELLPARAM_CASTRANGEDISPLAYOVERRIDE = 25,
	SPELLPARAM_CASTRADIUS = 26,
	SPELLPARAM_CASTRADIUSSECONDARY = 27,
	SPELLPARAM_CASTCONEDISTANCE = 30,
	SPELLPARAM_CASTCONEANGLE = 31,
	SPELLPARAM_LINEWIDTH = 32,
	SPELLPARAM_LINEDRAGLENGTH = 33,
	SPELLPARAM_CASTRANGEGROWTHMAX = 34,
	SPELLPARAM_CASTRANGEGROWTHSTARTTIME = 35,
	SPELLPARAM_CASTRANGEGROWTHDURATION = 36,
	SPELLPARAM_OVERRIDECASTTIME = 38,
	SPELLPARAM_CHANNELDURATION = 39,
	SPELLPARAM_CASTFRAME = 41,
	SPELLPARAM_MISSILESPEED = 42,
	SPELLPARAM_MISSILEACCEL = 43,
	SPELLPARAM_MISSILEMINSPEED = 44,
	SPELLPARAM_MISSILEMAXSPEED = 45,
	SPELLPARAM_MISSILELIFETIME = 46,
	SPELLPARAM_CHARGEUPDATEINTERVAL = 49,
};

enum class ScoreEvent
{
	NO_EVENT = 0,
	CHAMP_KILL = 1,
	CHAMP_ASSIST = 2,
	NODE_CAPTURE = 3,
	NODE_NEUTRALIZE = 4,
	NODE_KILL_OFFENSE = 5,
	TEAM_OBJECTIVE = 6,
	DEFEND_POINT_NEUTRALIZE = 7,
	NODE_KILL_DEFENSE = 8,
	NODE_TIME_DEFENSE = 9,
	LAST_STAND = 10,
	DEFENSIVE_ASSIST = 11,
	DEFENSIVE_KILL = 12,
	OFFENSIVE_ASSIST = 13,
	OFFENSIVE_KILL = 14,
	CHAMPION_KILL = 15,
	CHAMPION_ASSIST = 16,
	ACE = 17,
	QUEST_COMPLETE = 18,
	SENTINEL = 19,
	DUELIST = 20,
	GUARDIAN = 21,
	DOUBLE_KILL = 22,
	TRIPLE_KILL = 23,
	QUADRA_KILL = 24,
	PENTA_KILL = 25,
	KILLING_SPREE = 26,
	RAMPAGE = 27,
	UNSTOPPABLE = 28,
	DOMINATING = 29,
	GOD_LIKE = 30,
	LEGENDARY = 31,
	MINION_KILL = 32,
	SUPER_MINION_KILL = 33,
	AVENGER = 34,
	BOUNTY_HUNTER_2 = 35,
	BOUNTY_HUNTER_3 = 36,
	BOUNTY_HUNTER_4 = 37,
	BOUNTY_HUNTER_5 = 38,
	BOUNTY_HUNTER_6 = 39,
	BOUNTY_HUNTER_7 = 40,
	BOUNTY_HUNTER_8 = 41,
	PAYBACK = 42,
	ANGEL = 43,
	ARCH_ANGEL = 44,
	SCAVENGER_HUNT = 45,
	ZONE_CAPTURE = 46,
	ZONE_NEUTRALIZE = 47,
	SURVIVOR = 48,
	DEFENDER = 49,
	COUNTER = 50,
	OPPORTUNIST = 51,
	STRATEGIST = 52,
	FIRST_BLOOD = 53,
	VANGUARD = 54,
	MAJOR_RELIC_PICKUP = 55,
	NODE_CAPTURE_ASSIST = 56,
	NODE_NEUTRALIZE_ASSIST = 57,
};

enum class CharacterRecordParameterFloat
{
	CHARACTER_RECORD_PARAM_ATTACK_DELAY_CASTOFFSETPRECENT = 0,
	CHARACTER_RECORD_PARAM_BASE_PHYSICAL_DAMAGE = 1,
	CHARACTER_RECORD_PARAM_DAMAGE_PER_LEVEL = 2,
};

enum class InputLockType
{
	CAMERLOCKING = 1,
	MOVEMENT = 2,
	ABILTIES = 4,
	SUMMONERSPELLS = 8,
	SHOP = 16,
	CHAT = 32,
	MINIMAPMOVEMENT = 64,
	CAMERAMOVEMENT = 128,
};

enum class PrimaryAbilityResourceType
{
	PAR_MANA = 0,
	PAR_ENERGY = 1,
	PAR_NONE = 2,
	PAR_SHIELD = 3,
	PAR_BATTLEFURY = 4,
	PAR_DRAGONFURY = 5,
	PAR_RAGE = 6,
	PAR_HEAT = 7,
	PAR_GNARFURY = 8,
	PAR_FEROCITY = 9,
	PAR_BLOODWELL = 10,
	PAR_WIND = 11,
	PAR_OTHER = 13,
};

enum class RoundingStrategy
{
	NEAREST = 0,
	FLOOR = 1,
	CEIL = 2,
};

enum class QuestType
{
	PRIMARY_QUEST = 0,
	SECONDARY_QUEST = 1,
	OBJECTIVE = 2,
	CHARACTER_QUEST_CORKI = 3,
	NEW_CONTENT_NOTIFICATION = 4,
	SCORE_QUEST_DISPLAY = 5,
};

enum class LogicResultType
{
	COMPLETE = 0,
	FAILURE = 1,
	INVALID = 2,
	RUNNING = 3,
};

enum class MinionRoamState
{
	INACTIVE = 0,
	HOSTILE = 1,
	RUN_IN_FEAR = 2,
};

enum class CreatureType
{
	HEALER_CREATURE = 0,
	BRAWLER_CREATURE = 1,
	UNKNOWN_CREATURE = 2,
};

enum class FloatTextTypeEnum
{
	FLOATTEXT_Invulnerable = 0,
	FLOATTEXT_Special = 1,
	FLOATTEXT_Heal = 2,
	FLOATTEXT_ManaHeal = 3,
	FLOATTEXT_ManaDamage = 4,
	FLOATTEXT_Dodge = 5,
	FLOATTEXT_PhysicalDamageCritical = 6,
	FLOATTEXT_MagicalDamageCritical = 7,
	FLOATTEXT_TrueDamageCritical = 8,
	FLOATTEXT_Experience = 9,
	FLOATTEXT_Gold = 10,
	FLOATTEXT_Level = 11,
	FLOATTEXT_Disable = 12,
	FLOATTEXT_QuestReceived = 13,
	FLOATTEXT_QuestComplete = 14,
	FLOATTEXT_Score = 15,
	FLOATTEXT_PhysicalDamage = 16,
	FLOATTEXT_MagicalDamage = 17,
	FLOATTEXT_TrueDamage = 18,
	FLOATTEXT_EnemyPhysicalDamage = 19,
	FLOATTEXT_EnemyMagicalDamage = 20,
	FLOATTEXT_EnemyTrueDamage = 21,
	FLOATTEXT_EnemyPhysicalDamageCritical = 22,
	FLOATTEXT_EnemyMagicalDamageCritical = 23,
	FLOATTEXT_EnemyTrueDamageCritical = 24,
	FLOATTEXT_Countdown = 25,
	FLOATTEXT_OMW = 26,
	FLOATTEXT_Absorbed = 27,
	FLOATTEXT_Debug = 28,
	FLOATTEXT_PracticeToolTotal = 29,
	FLOATTEXT_PracticeToolLastHit = 30,
	FLOATTEXT_PracticeToolDPS = 31,
	FLOATTEXT_ScoreDarkStar = 32,
	FLOATTEXT_ScoreProject0 = 33,
	FLOATTEXT_ScoreProject1 = 34,
	FLOATTEXT_ShieldBonusDamage = 35,
};

enum class GameDifficultyType
{
	GAME_DIFFICULTY_NEWBIE = 0,
	GAME_DIFFICULTY_INTERMEDIATE = 1,
	GAME_DIFFICULTY_ADVANCED = 2,
	GAME_DIFFICULTY_UBER = 3,
	GAME_DIFFICULTY_TUTORIAL = 4,
	GAME_DIFFICULTY_INTRO = 5,
};

enum class DamageType
{
	PHYSICAL_DAMAGE = 0,
	MAGIC_DAMAGE = 1,
	TRUE_DAMAGE = 2,
	MIXED_DAMAGE = 3,
};

enum class CharacterRecordParameterInt
{
	CHARACTER_RECORD_PARAM_ABILITY_SLOT_0_CC = 3,
	CHARACTER_RECORD_PARAM_ABILITY_SLOT_1_CC = 4,
	CHARACTER_RECORD_PARAM_ABILITY_SLOT_2_CC = 5,
	CHARACTER_RECORD_PARAM_ABILITY_SLOT_3_CC = 6,
	CHARACTER_RECORD_PARAM_SKILL_ORDER = 7,
	CHARACTER_RECORD_PARAM_FIRST_ITEM = 8,
};

enum class CharacterRecordParameterString
{
	CHARACTER_RECORD_PARAM_FIRST_ITEM = 8,
};

enum class AITaskTopicType
{
	PUSHLANE = 0,
	GOTO = 1,
	DEFEND = 2,
	SUPPORT = 3,
	KILL = 4,
	WAIT = 5,
	UNKNOWN_TASK = 6,
};

enum class BehaveResult
{
	SUCCESS = 0,
	FAILURE = 1,
	RUNNING = 2,
};

enum class BuffType
{
	BUFF_Internal = 0,
	BUFF_Aura = 1,
	BUFF_CombatEnchancer = 2,
	BUFF_CombatDehancer = 3,
	BUFF_SpellShield = 4,
	BUFF_Stun = 5,
	BUFF_Invisibility = 6,
	BUFF_Silence = 7,
	BUFF_Taunt = 8,
	BUFF_Polymorph = 9,
	BUFF_Slow = 10,
	BUFF_Snare = 11,
	BUFF_Damage = 12,
	BUFF_Heal = 13,
	BUFF_Haste = 14,
	BUFF_SpellImmunity = 15,
	BUFF_PhysicalImmunity = 16,
	BUFF_Invulnerability = 17,
	BUFF_AttackSpeedSlow = 18,
	BUFF_NearSight = 19,
	BUFF_Currency = 20,
	BUFF_Fear = 21,
	BUFF_Charm = 22,
	BUFF_Poison = 23,
	BUFF_Suppression = 24,
	BUFF_Blind = 25,
	BUFF_Counter = 26,
	BUFF_Shred = 27,
	BUFF_Flee = 28,
	BUFF_Knockup = 29,
	BUFF_Knockback = 30,
	BUFF_Disarm = 31,
	BUFF_Grounded = 32,
	BUFF_Drowsy = 33,
	BUFF_Asleep = 34,
};

enum class BTInstanceType
{
	DELETE_SELF = 0,
	DISABLE_SELF = 1,
	ALWAYS_RUN = 2,
};

enum class AnnouncementEvent
{
	START_GAME_MESSAGE1 = 131,
	START_GAME_MESSAGE2 = 132,
	START_GAME_MESSAGE3 = 133,
	START_GAME_MESSAGE4 = 134,
	START_GAME_MESSAGE5 = 135,
	VICTORY_POINT_THRESHOLD1 = 151,
	VICTORY_POINT_THRESHOLD2 = 152,
	VICTORY_POINT_THRESHOLD3 = 153,
	VICTORY_POINT_THRESHOLD4 = 154,
	GAME_MODE_ANNOUNCEMENT1 = 155,
	GAME_MODE_ANNOUNCEMENT2 = 156,
	GAME_MODE_ANNOUNCEMENT3 = 157,
	GAME_MODE_ANNOUNCEMENT4 = 158,
	GAME_MODE_ANNOUNCEMENT5 = 159,
	GAME_MODE_ANNOUNCEMENT6 = 160,
	GAME_MODE_ANNOUNCEMENT7 = 161,
	GAME_MODE_ANNOUNCEMENT8 = 162,
	GAME_MODE_ANNOUNCEMENT9 = 163,
	GAME_MODE_ANNOUNCEMENT10 = 164,
	GAME_MODE_ANNOUNCEMENT11 = 165,
	GAME_MODE_ANNOUNCEMENT12 = 166,
	GAME_MODE_ANNOUNCEMENT13 = 167,
	GAME_MODE_ANNOUNCEMENT14 = 168,
	GAME_MODE_ANNOUNCEMENT15 = 169,
	GAME_MODE_ANNOUNCEMENT16 = 170,
};

enum class AIMissionTopicType
{
	BARON = 0,
	BOSS = 1,
	DEFEND = 2,
	SUPPORT = 3,
	KILL = 4,
	PUSH = 5,
	UNKNOWN_MISSION = 6,
};

enum class AIDifficultyType
{
	DIFFICULTY_NEWBIE = 0,
	DIFFICULTY_INTERMEDIATE = 1,
	DIFFICULTY_ADVANCED = 2,
	DIFFICULTY_UBER = 3,
	DIFFICULTY_TUTORIAL = 4,
	DIFFICULTY_INTRO = 5,
};